### ISSUE TITLE
error after scanning

### ISSUE THREAD

**Issue by arisawali2014** [skyf0l/WhatsAppTerm#9]
![gambar](https://user-images.githubusercontent.com/31904944/93974108-8a4ab280-fd9f-11ea-99c7-7c3bcd204e8c.png)
i got this error after scanning

**Comment by skyf0l** [comment]
Have you a good internet connection?
Sometimes, its timed out because of it

**Comment by arisawali2014** [comment]
![image](https://user-images.githubusercontent.com/31904944/95539899-c6297d00-0a19-11eb-8116-2f87ac759d82.png)
yes i have a good internet connection

**Comment by arisawali2014** [comment]
![image](https://user-images.githubusercontent.com/31904944/95541755-4d78ef80-0a1e-11eb-87e1-654afe85898d.png)
i fixed it by commenting the wait_until function on the decrypt_message 😃

**Comment by skyf0l** [comment]
Yes but if you don't wait the creation of the variable _hmac you can't decrypt some messages
However, in your trace, I can see you can open a connection because you receive s1, s2, s3 and s4 messages

I think it's the way I check if _hmac exist, I should set the variable to None by default and check if it is different to None instead of hasattr
May be hasattr not work on all python versions?

**Comment by arisawali2014** [comment]
ah i see.
but i think hasattr is builtin python.

btw, i want to ask, when will the quoted_message appear? i see that you update it when i try to recode my forked i got many error because quoted_message doesn't appear at the message

**Comment by arisawali2014** [comment]
![image](https://user-images.githubusercontent.com/31904944/95553942-8ffbf580-0a39-11eb-8ee9-0e78b65af2b6.png)
it's working now, 
i add condition of quotedMessage
![image](https://user-images.githubusercontent.com/31904944/95554022-adc95a80-0a39-11eb-944c-b654c2ae6816.png)

**Comment by skyf0l** [comment]
In which file you edit it ?
I remember i removed the quotedMessage parsing for now, in the latest merge

**Comment by arisawali2014** [comment]
client_messages on add_message

**Comment by skyf0l** [comment]
Okay, I find it in the latest commit, it's still in work
Now I'm putting this project on hold, but I will continue it very soon

**Comment by arisawali2014** [comment]
![image](https://user-images.githubusercontent.com/31904944/95569558-effd9680-0a4f-11eb-8213-3af5b469fd05.png)
do you have working send message? cause i try to port from [here](https://github.com/ndunks/WaJs/blob/a631015062d553b2a1d74c4e1baa47e5e6570261/src/whatsapp/index.ts#L84)
it doesn't send

**Comment by skyf0l** [comment]
yes, it's still in test and there is a bug because it doesn't work
you can try to solve it if you want and open a pull request if you succeed

**Comment by arisawali2014** [comment]
can i see it?

**Comment by skyf0l** [comment]
test function is [send_text_message](https://github.com/skyf0l/WhatsAppTerm/blob/master/WhatsAppApi/client.py#L154)

**Comment by arisawali2014** [comment]
ah i see
